// FairDrop — Order Model (MongoDB/Mongoose)
// Owner: Hari (25MCA025)
// Module: Orders (Module 2)
//
// Stores the full lifecycle of a delivery order:
//   placed → assigned → picked_up → delivered
//
// Each status change is recorded in status_history[] for audit.
// On delivery completion, the pay_calculation_result from Raihan's
// Pay Engine is stored directly on the order document.

const mongoose = require('mongoose');

// ── Valid status transitions ───────────────────────────────────────────────
// Enforced in the controller — prevents skipping steps or going backwards.

const VALID_TRANSITIONS = {
  placed: ['assigned'],
  assigned: ['picked_up'],
  picked_up: ['delivered'],
  delivered: [],               // Terminal state — no further transitions
};

// ── Status history entry ───────────────────────────────────────────────────

const statusHistorySchema = new mongoose.Schema(
  {
    status: { type: String, required: true },
    changed_at: { type: Date, default: Date.now },
    changed_by: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  },
  { _id: false }
);

// ── Delay context (sent to Pay Engine) ─────────────────────────────────────

const delayContextSchema = new mongoose.Schema(
  {
    type: {
      type: String,
      enum: ['traffic', 'restaurant', 'railway', 'none'],
      default: 'none',
    },
    verified: { type: Boolean, default: false },
    source: {
      type: String,
      enum: ['system_log', 'api_mock', 'none'],
      default: 'none',
    },
  },
  { _id: false }
);

// ── Main Order schema ──────────────────────────────────────────────────────

const orderSchema = new mongoose.Schema(
  {
    order_id: {
      type: String,
      unique: true,
      required: true,
      // Format: ORD-YYYYMMDD-NNNN (generated by Counter model)
    },

    // ── People involved ────────────────────────────────────────────────
    customer_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    restaurant_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    rider_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,  // Assigned after zone assignment finds an available rider
    },

    // ── Order details ──────────────────────────────────────────────────
    items: [
      {
        name: { type: String, required: true },
        quantity: { type: Number, required: true, min: 1 },
        price: { type: Number, required: true, min: 0 },
      },
    ],

    // ── Addresses ──────────────────────────────────────────────────────
    delivery_address: {
      label: { type: String, default: '' },
      latitude: { type: Number, required: true },
      longitude: { type: Number, required: true },
    },
    restaurant_address: {
      label: { type: String, default: '' },
      latitude: { type: Number, required: true },
      longitude: { type: Number, required: true },
    },

    // ── Delivery metrics ───────────────────────────────────────────────
    distance_km: { type: Number, required: true, min: 0 },
    zone_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Zone',
      default: null,
    },

    // ── Pay-related fields ─────────────────────────────────────────────
    is_surge_active: { type: Boolean, default: false },
    restaurant_wait_mins: { type: Number, default: 0 },
    delay_context: {
      type: delayContextSchema,
      default: () => ({ type: 'none', verified: false, source: 'none' }),
    },

    // ── Pay calculation result (from Raihan's Pay Engine) ──────────────
    // Stored after delivery completion when we call POST /api/pay/calculate
    pay_calculation_result: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },

    // ── Status tracking ────────────────────────────────────────────────
    status: {
      type: String,
      enum: ['placed', 'assigned', 'picked_up', 'delivered'],
      default: 'placed',
    },
    status_history: [statusHistorySchema],
  },
  {
    timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' },
  }
);

// ── Indexes ────────────────────────────────────────────────────────────────

orderSchema.index({ customer_id: 1, created_at: -1 });
orderSchema.index({ rider_id: 1, status: 1 });
orderSchema.index({ status: 1 });

// ── Export valid transitions so controller can use them ─────────────────────

orderSchema.statics.VALID_TRANSITIONS = VALID_TRANSITIONS;

const Order = mongoose.model('Order', orderSchema);

module.exports = Order;
